[package]
name = "stdext"
version = "0.0.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
single-threaded = []

[target.'cfg(unix)'.dependencies]
libc = "0.2"
